### ISSUE TITLE
Start the cluster with vagrant-module-collections in tests

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/ansible-gluster-collection#2]
### Acceptance:
 - [x] Have 3 nodes started and provisioned and configured with jclaveau.gluster role
 - [x] Have a working workflow using Vagrant snapshots
 - [x] Have a working workflow to chain tests based on states / starting point
 - [x] Have assertions for the configuration:
    - [x] check /etc/hosts
    - [x] check peers status
### Todo:
- [x] Create the tests installing the roles on the machine
- [x] Autopopulate the groups for vagrant
- [x] Use Vagrant snapshots if they are available or create them
- [x] Define a tasks/roles/playbooks architecture of testcases
    => written in Python or Ansible yaml?
  - [x] Experiment an API in Yaml based on roles/tasks
  - [x] ~Experiment an API in Yaml with new Python modules to control tests~
  - [x] ~If nothing works experiment an API in pure Python~
  - [x] Implementing auto adding vms to Ansible hosts and groups vagrant_hosts and state group
  - [x] Implementing auto adding vms to Ansible groups corresponding to the one used in the playbook
  - [x] Implement a way to define the starting point (state of the vms)
- [x] Implement a test launcher in Python (bash?) should exist to handle CLI parameters etc
  - Way to display Ansible result progressively: https://serverfault.com/a/1023944/554795
  - Erase previous line in stdout https://stackoverflow.com/questions/5290994/remove-and-replace-printed-items
  - [x] Implement `--skip-restore` for a faster development workflow
- [ ] Anticipate (No implementation) a loop for platforms
- [x] Anticipate (No implementation) a scale parameter for each state
- [ ] Prevent starting_state loops

### Should work (testing framework not integrated)
- [ ] Run one testcase with no starting_state
- [ ] Run one testcase with a starting_state (maybe having a starting_state)
- [ ] Run all testcases
